export const actionTypes = {
  GET_WEATHER_REQUEST: "GET_WEATHER_REQUEST",
  GET_WEATHER_SUCCESS: "GET_WEATHER_SUCCESS",
  GET_WEATHER_FAIL: "GET_WEATHER_FAIL",

  DAY_TEMPS_SUCCESS: "DAY_TEMPS_SUCCESS",
  DAY_TEMPS_FAIL: "DAY_TEMPS_FAIL",

  CHART_DATA_SUCCESS: "CHART_DATA_SUCCESS",
  CHART_DATA_FAIL: "CHART_DATA_FAIL",
};
