name: Deploy to github pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_KEY }}
      - name: Variable to dotenv
        uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
        with:
          node-version: ${{ matrix.node-version }}
          variableNamesByFilter: ^REACT\_(APP.\*)

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Packages
        run: npm install

      - name: Deploy
        run: git config --global user.name ${{secrets.USERNAME}}
          git config --global user.email ${{secrets.EMAIL}}
          git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USERNAME}}/react-weather-app
          npm run deploy
