name: Deploy to github pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_KEY }}
      - name: Variable to dotenv
        uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
        with:
          node-version: ${{ matrix.node-version }}
          variableNamesByFilter: ^REACT\_(APP.\*)
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
